# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            tagtog
tagline:          'The Text Annotation Tool to Train AI'
description:      'Official documentation for <a href="https://tagtog.net">tagtog</a>'
app_url:          https://www.tagtog.net
url:              http://docs.tagtog.net
baseurl:
sidebar_toc:
  - name: What's new
    pages:
      - updates

  - name: Tutorials
    pages:
      - quick_tutorials
      - ml
      - train-your-own-models

  - name: Web Application
    pages:
      - projects
      - document_pool
      - webeditor
      - collaboration
      - pdfann

  - name: API
    pages:
      - api
  - name: Concept Search
    pages:
      - search
      - search_queries

  - name: Formats
    pages:
      - formats
      - anndoc
      - dictionaries

  - name: On Premises
    pages:
      - on_premises_readme
      - sysadmin-premises


author:
  name:           'tagtog Sp. z o.o.'
  url:            https://twitter.com/tagtog_net

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jemoji

# Custom vars
version: 3.2019-W06.1
sidebar_home_link:  true
search_page:   false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/tagtog/

defaults:
- scope:
    path: "assets/img"
  values:
    image: true
